// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenFileInExternalApplication
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenFileInExternalApplication.f9fd1bfc-38ed-4785-9275-1e004a2b4d52";
        public const string Name = "OpenFileInExternalApplication";
        public const string Description = @"Open active document in external application with configured arguments";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "rybcom";
        public const string Tags = "";
    }
}
