// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenFileInExternalApplication
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OpenFileInExternalApplicationString = "ef73f942-3df3-4c5a-af39-fd64cfdefdbb";
        public static Guid OpenFileInExternalApplication = new Guid(OpenFileInExternalApplicationString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int OpenFileCommand = 0x0100;
    }
}